import DashboardLayout from "@/app/dashboardLayout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistInter.className} antialiased h-full`}>
      <body className="bg-background-gray-secondary_alt_2 h-full">
        <DashboardLayout children={children} />
      </body>
    </html>
  );
}
