export const topChannelsData = [
  {
    name: "Google",
    icon: "/images/social-icons/google.svg",
    visitors: "3.5K",
    revenues: "$4,220.00",
    sales: "3456",
    conversion: "2.59%",
  },
  {
    name: "X.com",
    icon: "/images/social-icons/x.svg",
    visitors: "3.5K",
    revenues: "$4,220.00",
    sales: "3456",
    conversion: "2.59%",
  },
  {
    name: "Github",
    icon: "/images/social-icons/github.svg",
    visitors: "3.5K",
    revenues: "$4,220.00",
    sales: "3456",
    conversion: "2.59%",
  },
  {
    name: "Vimeo",
    icon: "/images/social-icons/vimeo.svg",
    visitors: "3.5K",
    revenues: "$4,220.00",
    sales: "3456",
    conversion: "2.59%",
  },
  {
    name: "Facebook",
    icon: "/images/social-icons/facebook.svg",
    visitors: "3.5K",
    revenues: "$4,220.00",
    sales: "3456",
    conversion: "2.59%",
  },
];
